Global:
  # When enabled, players with respawn location (a bed or an respawn anchor) won't teleported to a spawn on death.
  Respect_Игрок_Beds: true
Настройки:
  # Sets spawn used by default.
  # If no other spawn is set, specified or available, the default one will be used.
  # Examples:
  # - When player types /spawn command without spawn name.
  #
  # [*] Игрокs always has access to the default spawn.
  Default_Spawn: default
Teleport_New_Игрокs:
  # Sets whether or not players вошёл the first time should be teleported to a certain spawn.
  Включено: false
  # Sets spawn ID for new players teleportation.
  # Spawn permission check will be ignored for new players.
  SpawnId: default
