# Uses legacy color codes with the & symbol.
# RGB can be used with & then the hex code, such as &#FFFF00.

# Displays when the region does not have a set display name.
Default: Нет

# Sets the region's display name.
# Format: region_id: "display name"
Regions:
  
  # Spawn
  world_spawn: Деревня Дарвин
  blacksmith: Кузница
  grotto: Грот
  enchantcenter: Центр зачарований
  treasury: Казна
  guild: Территория гильдии
  town_hall: Ратуша
  portal: Портал
  dungeonportal: Портал в подземелье
  rift: Разлом
  balloondock: Причал воздушных шаров
  quester_house: Дом квестера
  ascension_pedal: Пьедестал Вознесения
  
  # Приватный остров
  world_private_islands: Приватный остров
  world_private_islands_nether: Приватный остров
  
  # Dungeons 1
  loh_0: Лаборатория Ужасов
  loh_1: Лаборатория Ужасов
  loh_2: Лаборатория Ужасов
  loh_3: Лаборатория Ужасов
  loh_4: Лаборатория Ужасов
