KeepИнвентарь:
  # Sets whether or not Keep Инвентарь feature is enabled.
  Включено: true
  # Игрокs from the following permission groups will keep their items on death.
  Items_Ranks:
  - 'default'
  - 'vip'
  - 'mvp'
  - 'hero'
  - 'helper'
  - 'mod'
  - 'admin'
  - 'owner'
  # Игрокs from the following permission groups will keep their XP on death.
  Exp_Ranks:
  - '*'
JoinКомандаs:
  # Sets whether or not Join Командаs feature is enabled.
  Включено: false
  # List of commands to execute when player вошёл server for the first time.
  # Use 'player:' prefix to run command by a player.
  # Use '%player_name%' for a player name.
  # You can use PlaceholderAPI here.
  FirstJoin:
  - 'broadcast Добро пожаловать new player: %player_name%!'
  # List of commands to execute when player joins the server and has played before.
  # Use 'player:' prefix to run command by a player.
  # Use '%player_name%' for a player name.
  # You can use PlaceholderAPI here.
  Default: []
Anvil_Colors:
  # Sets whether or not Anvil Colors feature is enabled.
  # Игрокs with 'sunlight.extras.anvils.color' permission will be able to use colors on anvils.
  Включено: true
Sign_Colors:
  # Sets whether or not Sign Colors feature is enabled.
  # Игрокs with 'sunlight.extras.signs.color' permission will be able to use colors on signs.
  Включено: true
Physic_Explosions:
  # Sets whether or not Physic Explosions feature is enabled.
  # This will make blocks flying away on explosions.
  Включено: false
Chairs:
  # Sets whether or not Chairs feature is enabled.
  Включено: true
  # Sets whether or not Stair blocks can be used as chairs.
  Allow_Stairs: true
  # Sets whether or not Slab blocks can be used as chairs.
  Allow_Slabs: false
  # Sets whether or not Carpet blocks can be used as chairs.
  Allow_Carpets: false
  # Here you can add your own chairs blocks.
  Allowed_Blocks: []
ChestSort:
  # Sets whether or not Chest Sort feature is enabled.
  Включено: true
  # List of sorting order & rules.
  # Available values: IS_BLOCK, IS_ITEM, MATERIAL, AMOUNT, NAME
  Rules:
  - IS_BLOCK
  - IS_ITEM
  - MATERIAL
  - AMOUNT
  - NAME
AntiFarm:
  # Sets whether or not Enderman farms using minecart with endermite will be disabled.
  Endermite_Minecart: false
  # Sets whether or not Auto Fishing farms using note blocks (and not only them) will be disabled.
  AutoFishing: false
