debug: true
metrics: true
version-check: false
number-format: '#,###.#'
tick-speed: 1
namespace: betterhud
default-font-name: font.ttf
bossbar-line: 1
merge-boss-bar: false
disable-to-bedrock-player: true
build-folder-location: BetterHud/build
pack-type: none
enable-protection: false
enable-self-host: false
force-update: false
self-host-port: 8163
merge-other-folders: []
loading-head: random
default-hud:
- bars
- top_left
- quest_tracker
default-compass: []
disable-link-plugin: []
load-minecraft-default-textures: false
included-minecraft-list:
- block
- item
resourcepack-obfuscation: false
clear-build-folder: false
self-host-ip: '*'
legacy-serializer: ampersand
minecraft-jar-version: bukkit
default-popup: []
bossbar-resource-pack-line: 0
use-legacy-format: true
remove-default-hotbar: false
auto-save-time: 300
location-provide-time: 1
debug-level: assets
disable-legacy-offset: true
