hide_locked_discoveries_name: true
locked_discoveries_item: BOOK
locked_discoveries_item_custom_model_data: 70
data_auto_save_time: 600
progress_bar_placeholder:
  filled_symbol: '#b3e8b9&m '
  empty_symbol: '&8&m '
  amount: 20
mysql_database:
  enabled: false
  host: localhost
  port: 3306
  username: root
  password: root
  database: database
